name: Check for CODEOWNERS

on:
  # Runs on a pull request for the main branch (we use
  # 'pull_request_target' instead of 'pull_request' so
  # it also works for forks, since the secrets would
  # otherwise not be available for forks).
  pull_request_target:
    types:
      # Default events
      - opened
      - synchronize
      - reopened
      # But we also want to make sure a potential
      # exception request pull request is getting
      # closed if any was open
      - closed
    branches:
      - main
      - master
  # Runs on a merge group build
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  check:
    name: Check for CODEOWNERS
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}

    steps:
      - name: Welcome your new overlords
        if: ${{ endsWith(github.actor, '[bot]') }}
        run: echo "Robots get a pass" >> "$GITHUB_OUTPUT"; exit 0
          
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Find doesn't return non-0 for no results, but grep does.
      - name: Check for CODEOWNERS
        run: |
          find . -iname "CODEOWNERS" | grep .
        
