name: Semgrep
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: ghcr.io/temporalio/semgrep:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - name: Run semgrep ci
        run: semgrep ci
